## 六步法搭建神经网络模型

## 鸢尾花分类六步法复现

In [7]:
import tensorflow as tf
from sklearn import datasets
import numpy as np
import pandas as pd

In [2]:
x_train = datasets.load_iris().data

In [3]:
x_train

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
y_train = datasets.load_iris().target

In [5]:
y_train 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
np.random.seed(116) #设置随机种子，让每次结果都一样，方便对照
np.random.shuffle(x_train) #使用shuffle()方法，让输入x_train乱序
np.random.seed(116)  #设置随机种子，让每次结果都一样，方便对照
np.random.shuffle(y_train) #使用shuffle()方法，让输入y_train乱序
tf.random.set_seed(116) #设置全局随机种子

In [12]:
#第三步，models.Sequential()
model = tf.keras.models.Sequential([tf.keras.layers.Dense(3, activation = "softmax", kernel_regularizer = tf.keras.regularizers.l2()) #全连接层，三个神经元，激活函数为softmax,使用l2正则化
])


In [13]:

#第四步，model.compile()
model.compile(  #使用model.compile()方法来配置训练方法
    optimizer = tf.keras.optimizers.SGD(lr = 0.1), #使用SGD优化器，学习率为0.1
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = False), #配置损失函数
    metrics = ['sparse_categorical_accuracy'] #标注网络评价指标
)


In [14]:
#第五步，model.fit()
model.fit(  #使用model.fit()方法来执行训练过程，
    x_train, y_train, #告知训练集的输入以及标签，
    batch_size = 32, #每一批batch的大小为32，
    epochs = 500, #迭代次数epochs为500
    validation_split = 0.2, #从测试集中划分80%给训练集
    validation_freq = 20 #测试的间隔次数为20
)


Epoch 1/500
4/4 [==============================] - 0s 8ms/step - loss: 2.3173 - sparse_categorical_accuracy: 0.3417
Epoch 2/500
4/4 [==============================] - 0s 4ms/step - loss: 1.0797 - sparse_categorical_accuracy: 0.6167
Epoch 3/500
4/4 [==============================] - 0s 3ms/step - loss: 0.8429 - sparse_categorical_accuracy: 0.6250
Epoch 4/500
4/4 [==============================] - 0s 3ms/step - loss: 0.7448 - sparse_categorical_accuracy: 0.6667
Epoch 5/500
4/4 [==============================] - 0s 4ms/step - loss: 0.9843 - sparse_categorical_accuracy: 0.6417
Epoch 6/500
4/4 [==============================] - 0s 2ms/step - loss: 0.7808 - sparse_categorical_accuracy: 0.6583
Epoch 7/500
4/4 [==============================] - 0s 1ms/step - loss: 0.5961 - sparse_categorical_accuracy: 0.7250
Epoch 8/500
4/4 [==============================] - ETA: 0s - loss: 0.5631 - sparse_categorical_accuracy: 0.812 - 0s 2ms/step - loss: 0.5824 - sparse_categorical_accuracy: 0.7250
Epoch 9/50

4/4 [==============================] - 0s 1ms/step - loss: 0.3802 - sparse_categorical_accuracy: 0.9250
Epoch 67/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4052 - sparse_categorical_accuracy: 0.8667
Epoch 68/500
4/4 [==============================] - 0s 1ms/step - loss: 0.5520 - sparse_categorical_accuracy: 0.7250
Epoch 69/500
4/4 [==============================] - 0s 999us/step - loss: 0.4788 - sparse_categorical_accuracy: 0.8167
Epoch 70/500
4/4 [==============================] - 0s 1000us/step - loss: 0.3761 - sparse_categorical_accuracy: 0.9333
Epoch 71/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4550 - sparse_categorical_accuracy: 0.8250
Epoch 72/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4004 - sparse_categorical_accuracy: 0.9250
Epoch 73/500
4/4 [==============================] - 0s 999us/step - loss: 0.5146 - sparse_categorical_accuracy: 0.8167
Epoch 74/500
4/4 [==============================] - 0s 2ms/step - loss

4/4 [==============================] - 0s 1ms/step - loss: 0.3520 - sparse_categorical_accuracy: 0.9667
Epoch 134/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3700 - sparse_categorical_accuracy: 0.9333
Epoch 135/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3735 - sparse_categorical_accuracy: 0.9333
Epoch 136/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3584 - sparse_categorical_accuracy: 0.9333
Epoch 137/500
4/4 [==============================] - 0s 999us/step - loss: 0.4001 - sparse_categorical_accuracy: 0.9083
Epoch 138/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3530 - sparse_categorical_accuracy: 0.9583
Epoch 139/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4089 - sparse_categorical_accuracy: 0.9000
Epoch 140/500
4/4 [==============================] - 0s 6ms/step - loss: 0.5121 - sparse_categorical_accuracy: 0.7750 - val_loss: 0.3758 - val_sparse_categorical_accuracy: 1.0000
Epoch 1

4/4 [==============================] - 0s 6ms/step - loss: 0.3628 - sparse_categorical_accuracy: 0.9333 - val_loss: 0.4160 - val_sparse_categorical_accuracy: 0.9333
Epoch 201/500
4/4 [==============================] - 0s 999us/step - loss: 0.3575 - sparse_categorical_accuracy: 0.9417
Epoch 202/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4148 - sparse_categorical_accuracy: 0.8750
Epoch 203/500
4/4 [==============================] - 0s 1000us/step - loss: 0.3930 - sparse_categorical_accuracy: 0.9000
Epoch 204/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3465 - sparse_categorical_accuracy: 0.9750
Epoch 205/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3928 - sparse_categorical_accuracy: 0.9000
Epoch 206/500
4/4 [==============================] - 0s 999us/step - loss: 0.4302 - sparse_categorical_accuracy: 0.8417
Epoch 207/500
4/4 [==============================] - 0s 2ms/step - loss: 0.5203 - sparse_categorical_accuracy: 0.7750
Ep

Epoch 267/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3481 - sparse_categorical_accuracy: 0.9667
Epoch 268/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3558 - sparse_categorical_accuracy: 0.9333
Epoch 269/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4076 - sparse_categorical_accuracy: 0.8750
Epoch 270/500
4/4 [==============================] - 0s 1000us/step - loss: 0.4119 - sparse_categorical_accuracy: 0.9000
Epoch 271/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3590 - sparse_categorical_accuracy: 0.9417
Epoch 272/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3555 - sparse_categorical_accuracy: 0.9583
Epoch 273/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3999 - sparse_categorical_accuracy: 0.8833
Epoch 274/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3456 - sparse_categorical_accuracy: 0.9750
Epoch 275/500
4/4 [==============================] - 

4/4 [==============================] - 0s 1ms/step - loss: 0.3459 - sparse_categorical_accuracy: 0.9750
Epoch 335/500
4/4 [==============================] - 0s 1000us/step - loss: 0.3427 - sparse_categorical_accuracy: 0.9417
Epoch 336/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3421 - sparse_categorical_accuracy: 0.9667
Epoch 337/500
4/4 [==============================] - 0s 1000us/step - loss: 0.3449 - sparse_categorical_accuracy: 0.9417
Epoch 338/500
4/4 [==============================] - 0s 1000us/step - loss: 0.4189 - sparse_categorical_accuracy: 0.8583
Epoch 339/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3469 - sparse_categorical_accuracy: 0.9500
Epoch 340/500
4/4 [==============================] - 0s 5ms/step - loss: 0.4089 - sparse_categorical_accuracy: 0.8583 - val_loss: 0.3289 - val_sparse_categorical_accuracy: 1.0000
Epoch 341/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3863 - sparse_categorical_accuracy: 0.9083


Epoch 401/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3651 - sparse_categorical_accuracy: 0.9333
Epoch 402/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3480 - sparse_categorical_accuracy: 0.9583
Epoch 403/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3813 - sparse_categorical_accuracy: 0.9167
Epoch 404/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4448 - sparse_categorical_accuracy: 0.8583
Epoch 405/500
4/4 [==============================] - 0s 3ms/step - loss: 0.3864 - sparse_categorical_accuracy: 0.9083
Epoch 406/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3440 - sparse_categorical_accuracy: 0.9583
Epoch 407/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4250 - sparse_categorical_accuracy: 0.8667
Epoch 408/500
4/4 [==============================] - 0s 999us/step - loss: 0.3375 - sparse_categorical_accuracy: 0.9667
Epoch 409/500
4/4 [==============================] - 0

4/4 [==============================] - 0s 1ms/step - loss: 0.3566 - sparse_categorical_accuracy: 0.9417
Epoch 469/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3544 - sparse_categorical_accuracy: 0.9417
Epoch 470/500
4/4 [==============================] - 0s 1000us/step - loss: 0.3763 - sparse_categorical_accuracy: 0.9000
Epoch 471/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3349 - sparse_categorical_accuracy: 0.9500
Epoch 472/500
4/4 [==============================] - 0s 999us/step - loss: 0.5347 - sparse_categorical_accuracy: 0.7667
Epoch 473/500
4/4 [==============================] - ETA: 0s - loss: 0.7752 - sparse_categorical_accuracy: 0.750 - 0s 999us/step - loss: 0.4666 - sparse_categorical_accuracy: 0.8833
Epoch 474/500
4/4 [==============================] - 0s 999us/step - loss: 0.5124 - sparse_categorical_accuracy: 0.7833
Epoch 475/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3539 - sparse_categorical_accuracy: 0.9417

In [15]:
#第六步，model.summary()
model.summary() #打印神经网络结构，统计参数数目

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [16]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras import Model
from sklearn import datasets
import numpy as np

x_train = datasets.load_iris().data
y_train = datasets.load_iris().target

np.random.seed(116)
np.random.shuffle(x_train)
np.random.seed(116)
np.random.shuffle(y_train)
tf.random.set_seed(116)

class IrisModel(Model):
    def __init__(self):
        super(IrisModel, self).__init__()
        self.d1 = Dense(3, activation='softmax', kernel_regularizer=tf.keras.regularizers.l2())

    def call(self, x):
        y = self.d1(x)
        return y

model = IrisModel()

model.compile(optimizer=tf.keras.optimizers.SGD(lr=0.1),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
              metrics=['sparse_categorical_accuracy'])

model.fit(x_train, y_train, batch_size=32, epochs=500, validation_split=0.2, validation_freq=20)
model.summary()



Epoch 1/500
4/4 [==============================] - 0s 2ms/step - loss: 2.3173 - sparse_categorical_accuracy: 0.3417
Epoch 2/500
4/4 [==============================] - 0s 1ms/step - loss: 1.0797 - sparse_categorical_accuracy: 0.6167
Epoch 3/500
4/4 [==============================] - 0s 2ms/step - loss: 0.8429 - sparse_categorical_accuracy: 0.6250
Epoch 4/500
4/4 [==============================] - 0s 2ms/step - loss: 0.7448 - sparse_categorical_accuracy: 0.6667
Epoch 5/500
4/4 [==============================] - 0s 2ms/step - loss: 0.9843 - sparse_categorical_accuracy: 0.6417
Epoch 6/500
4/4 [==============================] - 0s 2ms/step - loss: 0.7808 - sparse_categorical_accuracy: 0.6583
Epoch 7/500
4/4 [==============================] - 0s 1ms/step - loss: 0.5961 - sparse_categorical_accuracy: 0.7250
Epoch 8/500
4/4 [==============================] - 0s 2ms/step - loss: 0.5824 - sparse_categorical_accuracy: 0.7250
Epoch 9/500
4/4 [==============================] - 0s 2ms/step - loss: 0

4/4 [==============================] - 0s 1ms/step - loss: 0.3802 - sparse_categorical_accuracy: 0.9250
Epoch 67/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4052 - sparse_categorical_accuracy: 0.8667
Epoch 68/500
4/4 [==============================] - 0s 2ms/step - loss: 0.5520 - sparse_categorical_accuracy: 0.7250
Epoch 69/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4788 - sparse_categorical_accuracy: 0.8167
Epoch 70/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3761 - sparse_categorical_accuracy: 0.9333
Epoch 71/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4550 - sparse_categorical_accuracy: 0.8250
Epoch 72/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4004 - sparse_categorical_accuracy: 0.9250
Epoch 73/500
4/4 [==============================] - 0s 2ms/step - loss: 0.5146 - sparse_categorical_accuracy: 0.8167
Epoch 74/500
4/4 [==============================] - 0s 2ms/step - loss: 0.384

4/4 [==============================] - 0s 2ms/step - loss: 0.3700 - sparse_categorical_accuracy: 0.9333
Epoch 135/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3735 - sparse_categorical_accuracy: 0.9333
Epoch 136/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3584 - sparse_categorical_accuracy: 0.9333
Epoch 137/500
4/4 [==============================] - 0s 3ms/step - loss: 0.4001 - sparse_categorical_accuracy: 0.9083
Epoch 138/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3530 - sparse_categorical_accuracy: 0.9583
Epoch 139/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4089 - sparse_categorical_accuracy: 0.9000
Epoch 140/500
4/4 [==============================] - 0s 10ms/step - loss: 0.5121 - sparse_categorical_accuracy: 0.7750 - val_loss: 0.3758 - val_sparse_categorical_accuracy: 1.0000
Epoch 141/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3577 - sparse_categorical_accuracy: 0.9500
Epoch 14

4/4 [==============================] - 0s 11ms/step - loss: 0.3628 - sparse_categorical_accuracy: 0.9333 - val_loss: 0.4160 - val_sparse_categorical_accuracy: 0.9333
Epoch 201/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3575 - sparse_categorical_accuracy: 0.9417
Epoch 202/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4148 - sparse_categorical_accuracy: 0.8750
Epoch 203/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3930 - sparse_categorical_accuracy: 0.9000
Epoch 204/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3465 - sparse_categorical_accuracy: 0.9750
Epoch 205/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3928 - sparse_categorical_accuracy: 0.9000
Epoch 206/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4302 - sparse_categorical_accuracy: 0.8417
Epoch 207/500
4/4 [==============================] - 0s 2ms/step - loss: 0.5203 - sparse_categorical_accuracy: 0.7750
Epoch 20

4/4 [==============================] - 0s 1ms/step - loss: 0.3515 - sparse_categorical_accuracy: 0.9500
Epoch 267/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3481 - sparse_categorical_accuracy: 0.9667
Epoch 268/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3558 - sparse_categorical_accuracy: 0.9333
Epoch 269/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4076 - sparse_categorical_accuracy: 0.8750
Epoch 270/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4119 - sparse_categorical_accuracy: 0.9000
Epoch 271/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3590 - sparse_categorical_accuracy: 0.9417
Epoch 272/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3555 - sparse_categorical_accuracy: 0.9583
Epoch 273/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3999 - sparse_categorical_accuracy: 0.8833
Epoch 274/500
4/4 [==============================] - 0s 999us/step - l

4/4 [==============================] - 0s 2ms/step - loss: 0.3528 - sparse_categorical_accuracy: 0.9500
Epoch 334/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3459 - sparse_categorical_accuracy: 0.9750
Epoch 335/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3427 - sparse_categorical_accuracy: 0.9417
Epoch 336/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3421 - sparse_categorical_accuracy: 0.9667
Epoch 337/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3449 - sparse_categorical_accuracy: 0.9417
Epoch 338/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4189 - sparse_categorical_accuracy: 0.8583
Epoch 339/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3469 - sparse_categorical_accuracy: 0.9500
Epoch 340/500
4/4 [==============================] - 0s 6ms/step - loss: 0.4089 - sparse_categorical_accuracy: 0.8583 - val_loss: 0.3289 - val_sparse_categorical_accuracy: 1.0000
Epoch 341

4/4 [==============================] - 0s 6ms/step - loss: 0.3787 - sparse_categorical_accuracy: 0.9250 - val_loss: 0.5941 - val_sparse_categorical_accuracy: 0.6000
Epoch 401/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3651 - sparse_categorical_accuracy: 0.9333
Epoch 402/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3480 - sparse_categorical_accuracy: 0.9583
Epoch 403/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3813 - sparse_categorical_accuracy: 0.9167
Epoch 404/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4448 - sparse_categorical_accuracy: 0.8583
Epoch 405/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3864 - sparse_categorical_accuracy: 0.9083
Epoch 406/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3440 - sparse_categorical_accuracy: 0.9583
Epoch 407/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4250 - sparse_categorical_accuracy: 0.8667
Epoch 408

4/4 [==============================] - 0s 2ms/step - loss: 0.3387 - sparse_categorical_accuracy: 0.9583
Epoch 468/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3566 - sparse_categorical_accuracy: 0.9417
Epoch 469/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3544 - sparse_categorical_accuracy: 0.9417
Epoch 470/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3763 - sparse_categorical_accuracy: 0.9000
Epoch 471/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3349 - sparse_categorical_accuracy: 0.9500
Epoch 472/500
4/4 [==============================] - 0s 1000us/step - loss: 0.5347 - sparse_categorical_accuracy: 0.7667
Epoch 473/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4666 - sparse_categorical_accuracy: 0.8833
Epoch 474/500
4/4 [==============================] - 0s 1ms/step - loss: 0.5124 - sparse_categorical_accuracy: 0.7833
Epoch 475/500
4/4 [==============================] - 0s 997us/step 

In [17]:
import tensorflow as tf
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras import Model

In [18]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 3s 0us/step


In [19]:
mnist

<module 'tensorflow.keras.datasets.mnist' from 'D:\\ProgramData\\Anaconda3\\envs\\tensorflow1\\lib\\site-packages\\tensorflow\\keras\\datasets\\mnist\\__init__.py'>

In [20]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [21]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [22]:
x_test

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [23]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [29]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [30]:
# 打印出训练集输入特征的第一个元素
print("x_train[0]:\n", x_train[0])

x_train[0]:
 [[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136
  175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253
  225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251
   93  82  82  56  39   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18 219 253 253 253 2

In [31]:
# 打印出训练集标签的第一个元素
print("y_train[0]:\n", y_train[0])

y_train[0]:
 5


In [32]:
# 打印出整个训练集输入特征形状
print("x_train.shape:\n", x_train.shape)
# 打印出整个训练集标签的形状
print("y_train.shape:\n", y_train.shape)
# 打印出整个测试集输入特征的形状
print("x_test.shape:\n", x_test.shape)
# 打印出整个测试集标签的形状
print("y_test.shape:\n", y_test.shape)


x_train.shape:
 (60000, 28, 28)
y_train.shape:
 (60000,)
x_test.shape:
 (10000, 28, 28)
y_test.shape:
 (10000,)


In [33]:
import tensorflow as tf

mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0  #归一化

In [34]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

In [35]:
model

In [36]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
              metrics=['sparse_categorical_accuracy'])

In [37]:
model.fit(x_train, y_train, batch_size=32, epochs=5, validation_data=(x_test, y_test), validation_freq=1)
model.summary()


Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2508 - sparse_categorical_accuracy: 0.9294 - val_loss: 0.1320 - val_sparse_categorical_accuracy: 0.9597
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1117 - sparse_categorical_accuracy: 0.9670 - val_loss: 0.1034 - val_sparse_categorical_accuracy: 0.9703
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0759 - sparse_categorical_accuracy: 0.9771 - val_loss: 0.0853 - val_sparse_categorical_accuracy: 0.9746
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0576 - sparse_categorical_accuracy: 0.9827 - val_loss: 0.0752 - val_sparse_categorical_accuracy: 0.9769
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0440 - sparse_categorical_accuracy: 0.9866 - val_loss: 0.0745 - val_sparse_categorical_accuracy: 0.9759
Model: "sequential_1"
_________________________________________________________________
Layer (

In [38]:
import tensorflow as tf

fashion = tf.keras.datasets.fashion_mnist
(x_train, y_train),(x_test, y_test) = fashion.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
              metrics=['sparse_categorical_accuracy'])

model.fit(x_train, y_train, batch_size=32, epochs=5, validation_data=(x_test, y_test), validation_freq=1)
model.summary()


4423680/4422102 [==============================] - 1s 0us/step
Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4978 - sparse_categorical_accuracy: 0.8235 - val_loss: 0.4111 - val_sparse_categorical_accuracy: 0.8541
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3727 - sparse_categorical_accuracy: 0.8650 - val_loss: 0.3897 - val_sparse_categorical_accuracy: 0.8608
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3339 - sparse_categorical_accuracy: 0.8784 - val_loss: 0.3747 - val_sparse_categorical_accuracy: 0.8637
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3115 - sparse_categorical_accuracy: 0.8853 - val_loss: 0.3635 - val_sparse_categorical_accuracy: 0.8676
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2954 - sparse_categorical_accuracy: 0.8913 - val_loss: 0.3558 - val_sparse_categorical_accuracy: 0.8735
Model: "sequential_2"
__________