## 基本变量

In [ ]:
import tensorflow as tf

In [2]:
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [3]:
my_var = tf.Variable(tf.ones([2,3]))

In [4]:
print(my_var)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>


In [5]:
tf.constant(5, dtype=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [6]:
tf.Variable(tf.constant(5, dtype=tf.float32))

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>

## 自动求导——tf.GradientTape

In [7]:
x = tf.constant(3.0)

In [8]:
x

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [12]:
x = tf.constant(3.0)
with tf.GradientTape() as g:  # （1）创建一个GradientTape对象
    g.watch(x)  # （2）监视watch要求导的变量
    y = x * x
dy_dx = g.gradient(y, x) # （3）对函数进行求导

In [13]:
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [15]:
with tf.GradientTape() as g:
    g.watch(x)
    with tf.GradientTape() as gg:
        gg.watch(x)
        y = x * x
dy_dx = gg.gradient(y, x)     # 求一阶导数
d2y_dx2 = g.gradient(dy_dx, x)    # 求二阶导数

In [16]:
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [19]:
print(d2y_dx2)

None


In [1]:
import tensorflow as tf
from sklearn.datasets import load_iris
from matplotlib import pyplot as plt
import numpy as np

In [2]:
np.random.seed(116) 

In [3]:
np.random.rand(4,3)

array([[0.37516863, 0.34870741, 0.92864348],
       [0.02913782, 0.00249151, 0.7839126 ],
       [0.04176065, 0.47799395, 0.36172369],
       [0.99285219, 0.20914299, 0.90539812]])

In [5]:
np.random.seed(116) 

In [6]:
np.random.rand(4,3)

array([[0.37516863, 0.34870741, 0.92864348],
       [0.02913782, 0.00249151, 0.7839126 ],
       [0.04176065, 0.47799395, 0.36172369],
       [0.99285219, 0.20914299, 0.90539812]])

In [8]:
# 导入数据，分别为输入特征和标签
x_data =load_iris().data
y_data =load_iris().target

In [9]:
x_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
x_data[:-30]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3